export const GET_VENDOR_LIST = "GET_VENDOR_LIST";
export const GET_VENDOR_LIST_COMPLETE = "GET_VENDOR_LIST_COMPLETE";
export const GET_VENDOR_LIST_ERROR = "GET_VENDOR_LIST_ERROR";

export const GET_FILTERS = "GET_FILTERS";
export const GET_FILTERS_COMPLETE = "GET_FILTERS_COMPLETE";
export const GET_FILTERS_ERROR = "GET_FILTERS_ERROR";